// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfn65ZiWk9LoX1F-c79y1TtrGbuqBw0bs',
    appId: '1:165809487820:android:b789ec0b96ed62a13d6769',
    messagingSenderId: '165809487820',
    projectId: 'dsc-connect-6f139',
    storageBucket: 'dsc-connect-6f139.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATgZU-0efhzk6YgBgXGicc7sqYoNGIEE4',
    appId: '1:165809487820:ios:754b14e9ff04c91f3d6769',
    messagingSenderId: '165809487820',
    projectId: 'dsc-connect-6f139',
    storageBucket: 'dsc-connect-6f139.appspot.com',
    androidClientId: '165809487820-84817frsoroh389spvaj5d6t3a2jhu05.apps.googleusercontent.com',
    iosClientId: '165809487820-eh09tj80uq3u708d4as5ces768epdqet.apps.googleusercontent.com',
    iosBundleId: 'com.sanyam.dscConnect',
  );
}
